name: Windows Build
on:
  push:
    branches: [ menzorg-windows-mac-buld ]
  pull_request:
    branches: [ menzorg-windows-mac-buld ]
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
env:
  USE_HARD_LINKS: false
  MIGRATIONS_DIR: .migrate
  ASSET_PREFIX: '.'
  npm_config_yes: true
  NEXT_PUBLIC_ENGINES: 1
  MIGRATIONS_ID_TYPE_SQL: bigint
  MIGRATIONS_ID_TYPE_GQL: bigint
  MIGRATIONS_HASURA_PATH: localhost:8080
  MIGRATIONS_HASURA_SSL: 0
  MIGRATIONS_HASURA_SECRET: myadminsecretkey
  NEXT_PUBLIC_DEEPLINKS_SERVER: http://localhost:3007
  NEXT_PUBLIC_GQL_PATH: localhost:3006/gql
  NEXT_PUBLIC_GQL_SSL: 0
  DEEPLINKS_HASURA_PATH: localhost:8080
  DEEPLINKS_HASURA_SSL: 0
  MIGRATIONS_DEEPLINKS_APP_URL: http://host.docker.internal:3007
  MIGRATIONS_DEEPLINKS_URL: http://host.docker.internal:3006
  DOCKER: 1
jobs:
  windows-build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15'
      - name: Configure Node caching
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-windows
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: install node tools
        run: npm install --global --production windows-build-tools@4.0.0
      - name: install node-gyp
        run: npm install --global node-gyp@latest
      - name: Set node config to use python2.7
        run: npm config set python python2.7
      - name: Install dc dependencies
        run: npm ci --force
      - name: Install electron dependencies
        run: cd electron && npm ci
      - name: pull dl
        run: cd node_modules/@deep-foundation && rm -r deeplinks && git clone https://github.com/deep-foundation/deeplinks.git && cd deeplinks && npm ci && npm run package:build && rm -r node_modules && rm -r package-lock.json && cd ../../..
      - name: build next
        run: npm run build && npm run export && npx rimraf electron/app && npx cap copy electron
      - name: Build distribution
        run: cd electron && npm run electron:pack
      - name: Create zip file
        run: |
          cd electron/dist
          tar.exe -a -c -f Deep.Case.zip "Deep.Case-setup.exe"
      - name: And a README (to work around GitHub double-zips)
        run: |
          echo "More information: https://deep.foundation" > electron/dist/README.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Deep.Case-Windows
          path: |
            electron/dist/Deep.Case.zip
            electron/dist/README.txt